### ISSUE TITLE
"Нам нужно больше веток, хозяин!"

### ISSUE THREAD

**Issue by volodymyr-kushnir** [UaSensei/BSA-JS#1]
Привіт.
Є пропозиція змінити розширення з **.txt** на **.md** в окремій гілці, використовуючи **"Fixes #1"** в якості повідомлення до комміту. Якщо на момент читання ця проблема вже неактуальна — закривай одразу.

**Comment by UaSensei** [comment]
Ок. А ще питання 2 текст заливати в цей ж репозиторій чи новий?

**Comment by volodymyr-kushnir** [comment]
Пакуй те все сюди, чого б нє. Можна заодно проект створити тут же ж на GitHub'і.
* Створити 1 статтю
* Створити 2 статтю
* Додати коментарі 1
* Додати коментарі 2

Шось типу такого. Потім карти можна конвертувати в **Issues** (Проблеми), потім їх можна вирішити і на виході вийде гарний репозиторій.

**Comment by UaSensei** [comment]
Ще хотів запитати.  Я прісля кожного разу як мурджу гілки видаляю (так як ви на уроці) і в результати тут відображає branch 1. Це ок? при перевірці це враховується? чи не потрібно видаляти branch?

**Comment by volodymyr-kushnir** [comment]
\* *"ти". ти — "ти", і я — "ти".*

На рахунок чи враховується при перевірці — важко сказати, бо так то перевірятиму не я, моє завдання — пересвідчитись шо лекція зайшла окей. Ну я б видаляв напевно. Основні мубть би залишив (feature/comments, patch/spellcheck і т. д.), а дрібні (hotfix/fix-commas-in-2nd-sentence) видаляв би.

**Comment by UaSensei** [comment]
Лекція чьотка! Мені сподобалась, все яксно і в крутій подачі. Теж дякую за те що тут допоміг! Якщо не важко можеш пояснити на рахунок коментарів я їх просто в файл маю залити чи на GitHub можна якось додавати комент до файлу? бо щось не може розібратися сорі що трохи напрягаю

**Comment by volodymyr-kushnir** [comment]
В файл. Файл буде виглядати приблизно так:

**Назва статті**
Стаття
------
*Коментар1*
*Коментар2*

Важливо додавати коментарі окремими коммітами в окрему гілку.

**Comment by UaSensei** [comment]
Супер дякую за допомогу!!!!
